### ISSUE TITLE
Ideas about multi-language support

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [rejetto/hfs-aborted-see-new-repo#4]
I have some ideas about multi-language support for HFS.

For translating HFS into other language, when I visit Explore++ website, I get an idea. On this website I found the developer provide many individual translation files to download when I click the [Translations](https://explorerplusplus.com/translations) page. Then I found it also provide the way of translating:
1. Provide English CSV/XLS files as a template
2. Let users submit the translation by email
3. Complie a DLL based on translated sheet

For character encoding, I think you can provide an option to let user choose which code to be used, such as UTF-8, Big5, GBK, JIS X 0213, KS X 1001 etc. Then both main app and HTML client use this encoding for transfer. On HTML page this can be used via a method as `<meta charset="UTF-8"/>`.

**Comment by XCanG** [comment]
Rather than separate translation (as you will send on email), better is cooperate to translate program on multiple languages. Community may vote for best translation, because translation may be variative in some cases.
I'll give two examples: https://crowdin.com/ and https://www.transifex.com/
I translate some projects both on crowdin and transifex and may say, that crowdin is more convinient for that, but both services are good.

**Comment by KrasnayaPloshchad** [comment]
@XCanG That’s good idea for translating.

**Comment by rejetto** [comment]
moved to https://github.com/rejetto/hfs
